function DrawValue( obj )

% And now apply a new mask over the previous one

Screen('FillOval',obj.wPtr,...
    obj.valueCurrentColor,...
    obj.Rect);

% Screen('FillArc',obj.wPtr,...
%     obj.valueCurrentColor,...
%     obj.Rect,...
%     0,...
%     obj.value*360/100);

end % function
