function DrawValue( obj )

% And now apply a new mask over the previous one
Screen('FillArc',obj.wPtr,...
    obj.valueCurrentColor,...
    obj.Rect,...
    0,...
    obj.value*360/100);

end % function
